# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/export.ipynb.

# %% auto 0
__all__ = [
    "obtain_function_name_and_test_flag",
    "transform_test_source_for_docs",
    "replace_folder_in_path",
    "set_paths_nb_processor",
    "NbMagicProcessor",
    "NbMagicExporter",
    "nbm_export",
    "nbm_export_all_paths",
    "parse_argv_and_run_nbm_export_all_paths",
    "nbm_export_cli",
    "process_cell_for_nbm_update",
    "nbm_update",
    "nbm_update_all_paths",
    "parse_argv_and_run_nbm_update_all_paths",
    "nbm_update_cli",
]

# %% ../nbs/export.ipynb 2
# Standard
import shlex
import os
import ast
from pathlib import Path
import joblib
import warnings
from typing import List

# hello
import argparse

# hello
import sys

# 3rd party
from matplotlib.pylab import f
from sklearn.utils import Bunch
from nbdev.processors import Processor, NBProcessor
from nbdev.export import nb_export
from nbdev.sync import _update_mod, _mod_files
from nbdev.doclinks import nbglob
from execnb.nbio import mk_cell, read_nb, write_nb, NbCell
from fastcore.all import globtastic

# nbmodular
from .utils import create_or_get_logger, get_config
import nbmodular.test_utils as tst
from .cell2func import CellProcessor


# %% ../nbs/export.ipynb 5
def obtain_function_name_and_test_flag(line, cell):
    root = ast.parse(cell)
    name = [x.name for x in ast.walk(root) if isinstance(x, ast.FunctionDef)]
    argv = shlex.split(line, posix=(os.name == "posix"))[1:]
    is_test = "--test" in argv

    if len(name) > 0:
        function_name = name[0]
    else:
        function_name = argv[0] if len(argv) > 0 else ""
        if function_name.startswith("-"):
            function_name = ""

    if function_name == "":
        raise RuntimeError("Couldn't find function name.")

    return function_name, is_test


# %% ../nbs/export.ipynb 9
def transform_test_source_for_docs(source: str, idx: int, tab_size: int) -> str:
    """Transforms cell code in order to be exported to test notebook.

    The resulting test code doesn't have the function's signature, and has one
    less level of indentation.

    Parameters
    ----------
    source_lines : str
        Original source code, in a single string.
    idx : int
        Index in the function's array of cells. The function can span across
        multiple cells in the notebook, the first cell containing the function's
        signature and possibly the initial part of the body, and the remaining cells
        containing the remaining parts of the body.
    tab_size : int
        Number of spaces used for indentation.

    Returns
    -------
    str
        Resulting test code, without signature, and with one less level of indentation.
    """
    start = 1 if idx == 0 else 0
    source_lines = source.splitlines()
    transformed_lines = []
    for line in source_lines[start:]:
        transformed_lines.append(
            line[tab_size:] if line.startswith(" " * tab_size) else line
        )
    return "\n".join(transformed_lines)


# %% ../nbs/export.ipynb 14
from pathlib import Path


def replace_folder_in_path(
    path: Path,
    original_folder: str,
    new_folder: str,
):
    """
    Replace a folder in the given path with a new folder.

    Parameters
    ----------
    path : Path
        The original path to modify.
    original_folder : str
        The name of the folder to replace.
    new_folder : str
        The name of the new folder.

    Returns
    -------
    Path
        The modified path with the folder replaced.
    """
    if original_folder in path.parent.parts:
        # we take the last index instead of the first one
        # in case the folder is a subfolder of another one with same name
        # this happens when testing our nbmodular library
        index = -path.parent.parts[-1::-1].index(original_folder) - 1
        index = len(path.parent.parts) + index
        parts = (
            path.parent.parts[:index] + (new_folder,) + path.parent.parts[index + 1 :]
        )
        new_path = Path().joinpath(*parts) / path.name
    else:
        new_path = path
    return new_path


# %% ../nbs/export.ipynb 18
def set_paths_nb_processor(
    nb_processor: "NbMagicExporter | Bunch",
    path: str | Path,
    code_cells_path: str | Path = ".nbmodular",
    changed_path: str | Path | None = None,
) -> None:
    """
    Set the paths for the notebook processor.

    Parameters:
        nb_processor (NbMagicExporter): The notebook processor object.
        path (str): The path of the notebook file.
    """
    nb_processor.path = Path(path)
    nb_processor.file_name_without_extension = nb_processor.path.stem

    # import ipdb
    # ipdb.set_trace()
    config = get_config()
    nb_processor.root_path = config.config_path.parent
    nb_processor.nbs_path = config["nbs_path"]
    nb_processor.nbm_path = config["nbm_path"]
    nb_processor.lib_path = config["lib_path"]

    # In diagram: nbs/nb.ipynb
    nb_processor.dest_nb_path = replace_folder_in_path(
        nb_processor.path, nb_processor.nbm_path, nb_processor.nbs_path
    )
    nb_processor.dest_nb_path.parent.mkdir(parents=True, exist_ok=True)

    # In diagram: nbs/test_nb.ipynb
    nb_processor.test_dest_nb_path = (
        nb_processor.dest_nb_path.parent
        / f"test_{nb_processor.file_name_without_extension}.ipynb"
    )
    # In diagram: .nbs/nb.ipynb
    nb_processor.tmp_nb_path = replace_folder_in_path(
        nb_processor.path, nb_processor.nbm_path, ".nbs"
    )
    nb_processor.tmp_nb_path.parent.mkdir(parents=True, exist_ok=True)

    # step 2 (beginning) in diagram
    # In diagram: .nbs/_nb.ipynb
    nb_processor.duplicate_tmp_path = (
        nb_processor.tmp_nb_path.parent / f"_{nb_processor.tmp_nb_path.name}"
    )

    # step 3 in diagram
    # In diagram: .nbs/nb.ipynb
    nb_processor.tmp_dest_nb_path = (
        nb_processor.tmp_nb_path.parent / nb_processor.dest_nb_path.name
    )
    # In diagram: .nbs/test_nb.ipynb
    nb_processor.tmp_test_dest_nb_path = (
        nb_processor.tmp_nb_path.parent / nb_processor.test_dest_nb_path.name
    )

    # step 5 (beginning) in diagram
    nb_processor.duplicate_dest_nb_path = (
        nb_processor.dest_nb_path.parent / f"_{nb_processor.dest_nb_path.name}"
    )

    # python module paths
    if nb_processor.nbm_path in nb_processor.path.parent.parts:
        index = nb_processor.path.parent.parts.index(nb_processor.nbm_path)
    else:
        raise RuntimeError(f"{nb_processor.nbm_path} not found in {nb_processor.path}")
    parent_parts = nb_processor.path.parent.parts[index + 1 :]
    # module paths
    nb_processor.dest_python_path = nb_processor.root_path / "/".join(
        (
            nb_processor.lib_path,
            *parent_parts,
            f"{nb_processor.file_name_without_extension}.py",
        )
    )
    nb_processor.dest_python_path.parent.mkdir(parents=True, exist_ok=True)
    # test module paths
    nb_processor.test_dest_python_path = nb_processor.root_path / "/".join(
        (
            nb_processor.lib_path,
            "tests",
            *parent_parts,
            f"test_{nb_processor.file_name_without_extension}.py",
        )
    )
    nb_processor.test_dest_python_path.parent.mkdir(parents=True, exist_ok=True)

    # cell_types
    nb_processor.cell_types_file_path = nb_processor.root_path / "/".join(
        (
            code_cells_path,
            *parent_parts,
            f"cell_types_{nb_processor.file_name_without_extension}.pk",
        )
    )
    nb_processor.cell_types_file_path.parent.mkdir(parents=True, exist_ok=True)

    # to be used in default_exp cell (see NBExporter)
    nb_processor.dest_module_path = ".".join(
        (*parent_parts, nb_processor.file_name_without_extension)
    )
    nb_processor.test_dest_module_path = ".".join(
        ("tests", *parent_parts, f"test_{nb_processor.file_name_without_extension}")
    )


# %% ../nbs/export.ipynb 27
class NbMagicProcessor(Processor):
    """
    Processor class that stores information and code for cells using the magic
    commands recognized by `CellProcessor`

    Parameters
    ----------
    path : str
        The path to the notebook file.
    nb : Notebook object, optional
        The notebook object. If not provided, it will be read from the file.
    logger : Logger, optional
        The logger object. If not provided, a new logger will be created.
    log_level : str, optional
        The log level for the logger. Defaults to "INFO".
    """

    def __init__(
        self,
        path,
        nb=None,
        logger_name="nbmodular",
        log_level="INFO",
        from_notebook=False,
        restrict_inputs=False,
        api=True,
    ):
        nb = read_nb(path) if nb is None else nb
        super().__init__(nb)
        self.logger = create_or_get_logger(logger_name, log_level)
        self.logger.info(f"Analyzing code from notebook {path}")
        self.cell_processor = CellProcessor(
            path=path, run=from_notebook, restrict_inputs=restrict_inputs, api=api
        )
        self.cell_processor.change_file_name = False
        self.cell_processor.set_run_tests(False)
        self.from_notebook = from_notebook

    def cell(self, cell):
        """
        Process a notebook cell.

        Parameters
        ----------
        cell : Cell object
            The notebook cell to process.
        """
        source_lines = cell.source.splitlines() if cell.cell_type == "code" else []
        if len(source_lines) > 0 and source_lines[0].strip().startswith("%%"):
            line = source_lines[0]
            words = line.split()
            command = words[0][2:]
            if command in self.cell_processor.magic_commands_list:
                line = " ".join(words[1:])
                self.cell_processor.process_function_call(
                    line=line,
                    cell="\n".join(source_lines[1:]) if len(source_lines) > 1 else "",
                    add_call=True,
                    is_class=command == "class",
                )
        elif len(source_lines) > 0 and source_lines[0].strip().startswith("%"):
            # We process here those cells that start with a line magic command.
            # Those are not processed when calling self.cell_processor.process_function_call
            # And they *usually* affect the whole cell_processor, not just one of its functions
            # Therefore, they are used here to update the state of self.cell_processor
            # By adding / modifying attributes modified by these line magics.
            line = source_lines[0].strip()[1:]
            # source = "\n".join(source_lines[1:])
            command, remaining_line = line.split()
            # function_name, kwargs = self.cell_processor.parse_signature(remaining_line)
            if command == "keep_original":
                self.cell_processor.api = False
            elif command == "file_path":
                self.cell_processor.set_file_path(remaining_line)
                self.cell_processor.change_file_name = True


# %% ../nbs/export.ipynb 33
def is_jupytext_header(text: str) -> bool:
    """Determine if the jupytext header has been written at beginning of notebook."""
    lines = text.split("\n")
    detected_starting_comment = False
    detected_jupyter_header = False
    in_jupyter_section = False

    for i, line in enumerate(lines):
        if line.strip() == "# ---" and not detected_starting_comment:
            detected_starting_comment = True
        if line.strip() == "# jupyter:" and detected_starting_comment:
            in_jupyter_section = True
            continue
        if line.strip() == "# ---" and in_jupyter_section:
            detected_jupyter_header = True
            break

    return detected_jupyter_header


class NbMagicExporter(Processor):
    """
    Processor class for exporting notebooks with magic commands.

    Parameters:
    ----------
    path : str
        The path to the notebook file.
    nb : fastcore.basics.AttrDict, optional
        The notebook object. If not provided, it will be read from the file specified by `path`.
    code_cells_file_name : str, optional
        The name of the file to store the code cells. If not provided, it will be set to the file name without extension.
    code_cells_path : str, optional
        The path to the directory where the code cells file will be stored. Default is ".nbmodular".
    execute : bool, optional
        Flag indicating whether to execute the notebook before exporting. Default is True.
    logger : logging.Logger, optional
        The logger object to use for logging. If not provided, a new logger will be created.
    log_level : str, optional
        The log level for the logger. Default is "INFO".
    tab_size : int, optional
        The number of spaces to use for indentation. Default is 4.
    """

    def __init__(
        self,
        path,
        nb=None,
        code_cells_file_name=None,
        code_cells_path=".nbmodular",
        execute=True,
        logger_name="nbmodular",
        log_level="INFO",
        tab_size=4,
        from_notebook=False,
        restrict_inputs=False,
        api=True,
    ):
        nb = read_nb(path) if nb is None else nb
        super().__init__(nb)
        self.logger = create_or_get_logger(logger_name, log_level)

        self.logger.info(f"Analyzing code from notebook {path}")
        self.nb_magic_processor = NbMagicProcessor(
            path,
            nb=nb,
            logger_name=logger_name,
            log_level=log_level,
            from_notebook=from_notebook,
            restrict_inputs=restrict_inputs,
            api=api,
        )
        set_paths_nb_processor(
            self,
            path,
            code_cells_path=code_cells_path,
            changed_path=(
                self.nb_magic_processor.cell_processor.file_path
                if self.nb_magic_processor.cell_processor.change_file_name
                else None
            ),
        )
        code_cells_file_name = (
            self.file_name_without_extension
            if code_cells_file_name is None
            else code_cells_file_name
        )

        NBProcessor(path, self.nb_magic_processor, rm_directives=False, nb=nb).process()

        self.function_names = {}
        self.test_function_names = {}
        self.cells = []
        self.test_cells = []
        self.doc_cells = []

        self.default_exp_cell = mk_cell(f"#|default_exp {self.dest_module_path}")
        self.default_test_exp_cell = mk_cell(
            f"#|default_exp {self.test_dest_module_path}"
        )

        # list of types of cells, to be used by importer
        # can be "code", "test", "original"
        self.cell_types = []

        # other
        self.tab_size = tab_size

        self.in_first_cell = True

    def cell(self, cell):
        """
        Process a cell.

        Parameters:
        ----------
        cell : nbdev.NbCell
            The cell to process.
        """

        # Filter specific for jupytext translated notebooks
        # if self.in_first_cell:
        #     self.in_first_cell = False
        #     if cell.cell_type == "code" and is_jupytext_header(cell.source):
        #         nb = self.nb.copy()
        #         nb.cells = self.nb.cells[1:]
        #         write_nb(nb, self.path)
        #         return

        source_lines = cell.source.splitlines() if cell.cell_type == "code" else []
        is_test = False
        cell_type = "original"
        keep_original_in_documentation = False
        if (
            self.nb_magic_processor.cell_processor.api
            and len(source_lines) > 0
            and source_lines[0].strip().startswith("%%")
        ):
            line = source_lines[0]
            source = "\n".join(source_lines[1:])
            to_export = False
            is_test = False
            if line.startswith("%%function") or line.startswith("%%method"):
                function_name, is_test = obtain_function_name_and_test_flag(
                    line, source
                )
                function_names = (
                    self.test_function_names if is_test else self.function_names
                )
                if function_name in function_names:
                    function_names[function_name] += 1
                else:
                    function_names[function_name] = 0
                idx = function_names[function_name]
                self.logger.debug(f"{function_name}, {idx}, is test: {is_test}")
                code_cells = (
                    self.nb_magic_processor.cell_processor.test_code_cells
                    if is_test
                    else self.nb_magic_processor.cell_processor.code_cells
                )
                function_info = (
                    self.nb_magic_processor.cell_processor.function_info
                    if is_test
                    else self.nb_magic_processor.cell_processor.function_info
                )
                if function_name not in code_cells:
                    raise RuntimeError(
                        f"Function {function_name} not found in code_cells dictionary with keys {code_cells.keys()}"
                    )
                function_info = function_info[function_name]
                code_cells = code_cells[function_name]
                if len(code_cells) <= idx:
                    raise RuntimeError(
                        f"Function {function_name} has {len(code_cells)} cells, which is lower than index {idx}."
                    )
                code_cell = code_cells[idx]
                self.logger.debug("code:")
                # should we use code_cell for storing valid flag, or function_info?
                # (this depends on whether the valid flag needs to be saved as part
                # of the pickle file for code_cells)
                self.logger.debug(f"{code_cell.code}valid: {code_cell.valid}")
                keep_original_in_documentation = (
                    function_info.keep_original_in_documentation
                )
                if code_cell.valid and function_info.api:
                    source = code_cell.code
                    to_export = True
            elif line.startswith("%%include") or line.startswith("%%class"):
                to_export = True
            if to_export:
                line = line.replace("%%", "#@@")
                code_source = line + "\n" + source
                code_source = "#|export\n" + code_source
                doc_source = (
                    "#|export\n" + source
                )  # doc_source does not include first line with #@@
                new_cell = NbCell(cell.idx_, cell)
                new_cell["source"] = code_source
                if is_test:
                    self.test_cells.append(new_cell)
                    cell_type = "test"
                else:
                    self.cells.append(new_cell)
                    cell_type = "code"
            else:
                if keep_original_in_documentation:
                    doc_source = cell.source
                else:
                    doc_source = source  # doc_source does not include first line with %% (? to think about)
                # doc_source = source  # doc_source does not include first line with %% (? to think about)
            if is_test:
                doc_source = transform_test_source_for_docs(
                    code_cell.code, idx, self.tab_size
                )
            cell["source"] = doc_source
            self.doc_cells.append(cell)
        elif (
            self.nb_magic_processor.cell_processor.api
            and len(source_lines) > 0
            and source_lines[0].strip().startswith("%")
            and "--keep" in source_lines[0].strip()
        ):
            self.nb_magic_processor.cell_processor.code_cells.append(cell)

        self.cell_types.append(cell_type)

    def end(self):
        """
        Perform final processing steps.
        """
        # store cell_types for later use by NBImporter
        joblib.dump(self.cell_types, self.cell_types_file_path)

        write_nb(self.nb, self.tmp_nb_path)
        self.nb.cells = self.cells
        lib_path = Path(self.lib_path).absolute()
        if len(self.cells) > 0:
            self.nb.cells = [self.default_exp_cell] + self.cells
            write_nb(self.nb, self.dest_nb_path)
            nb_export(self.dest_nb_path, lib_path=lib_path)
        if len(self.test_cells) > 0:
            self.nb.cells = [self.default_test_exp_cell] + self.test_cells
            write_nb(self.nb, self.test_dest_nb_path)
            nb_export(self.test_dest_nb_path, lib_path=lib_path)

        # step 2 (beginning) in diagram
        if self.tmp_nb_path.exists():
            self.tmp_nb_path.rename(self.duplicate_tmp_path)

        # step 3 in diagram
        if self.dest_nb_path.exists():
            self.dest_nb_path.rename(self.tmp_dest_nb_path)
        if self.test_dest_nb_path.exists():
            self.test_dest_nb_path.rename(self.tmp_test_dest_nb_path)

        # step 2 (end) in diagram
        if self.duplicate_tmp_path.exists():
            self.duplicate_tmp_path.rename(self.dest_nb_path)


# %% ../nbs/export.ipynb 35
def nbm_export(
    path,
    **kwargs,
):
    """
    Export a notebook to its corresponding Python module.

    Parameters:
    ----------
    path : str or Path
        The path to the notebook file.
    **kwargs : dict, optional
        Additional keyword arguments passed to NbMagicExporter. These can include:
        - code_cells_file_name : str, optional
            The name of the file to store the code cells. If not provided, it will be set to the file name without extension.
        - code_cells_path : str, optional
            The path to the directory where the code cells file will be stored. Default is ".nbmodular".
        - execute : bool, optional
            Flag indicating whether to execute the notebook before exporting. Default is True.
        - logger_name : str, optional
            The name of the logger. Default is "nbmodular".
        - log_level : str, optional
            The log level for the logger. Default is "INFO".
        - tab_size : int, optional
            The number of spaces to use for indentation. Default is 4.
        - from_notebook : bool, optional
            Flag indicating whether the export is from a notebook. Default is False.
    """
    path = Path(path)
    nb = read_nb(path)
    processor = NbMagicExporter(
        path,
        nb=nb,
        **kwargs,
    )
    NBProcessor(path, processor, rm_directives=False, nb=nb).process()


# %% ../nbs/export.ipynb 44
def nbm_export_all_paths(path, **kwargs):
    # To test:
    # original_path = Path(path)
    # nbm_folder = config["nbm_path"]
    # if nbm_folder not in original_path.parts and (original_path / nbm_folder).exists:
    #     path = str (original_path / nbm_folder)
    files = nbglob(path=path, as_path=True).sorted("name")
    for f in files:
        nbm_export(f, **kwargs)


def parse_argv_and_run_nbm_export_all_paths(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Export notebooks to their corresponding python modules."
    )
    parser.add_argument("--path", type=str, default=None, help="Path to notebook")
    parser.add_argument(
        "--from-notebook",
        action="store_true",
        help="Flag indicating whether the export is from a notebook.",
    )
    parser.add_argument(
        "--restrict-inputs",
        action="store_true",
        help="Flag indicating whether to restrict inputs.",
    )
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.path is None:
        args.path = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Exporting notebooks from path: {args.path}")
    nbm_export_all_paths(
        args.path,
        from_notebook=args.from_notebook,
        restrict_inputs=args.restrict_inputs,
    )


def nbm_export_cli():
    parse_argv_and_run_nbm_export_all_paths(sys.argv[1:])


# %% ../nbs/export.ipynb 55
def process_cell_for_nbm_update(cell: NbCell):
    """
    Processes a Jupyter notebook cell to update it for nbmodular.
    This function checks the source of a notebook cell for specific directives and magic lines.
    It ensures that the cell contains the required directives and updates the cell's source
    accordingly. If the required directives or magic lines are not found, it raises an error.
    Parameters
    ----------
    cell : NbCell
        The notebook cell to be processed. It is expected to have attributes `source` and `cell_type`.
    Raises
    ------
    ValueError
        If the directive line or magic line is not found in the cell.
    warnings.warn
        If a line starting with `#@@` or `# @@` is found with a word that is not in
        ['function', 'method', 'include', 'class'].
    Notes
    -----
    - The function looks for lines starting with `#|` as directives.
    - It then expects a line starting with `#@@` or `# @@` to follow the directive.
    - The function modifies the cell's source by replacing the `#@@` or `# @@` line with a magic line (`%%`).
    """

    source_lines = cell.source.splitlines() if cell.cell_type == "code" else []
    found_directive = False
    found_magic = False
    for line_number, line in enumerate(source_lines):
        line = line.strip()
        if len(line) > 0:
            if found_directive:
                if line.startswith("#@@") or line.startswith("# @@"):
                    line = line[3:] if line.startswith("#@@") else line[4:]
                    words = line.split()
                    if len(words) > 0 and words[0] not in [
                        "function",
                        "method",
                        "include",
                        "class",
                    ]:
                        warnings.warn(
                            f"Found #@@ with a word after that, and this word is not in ['function', 'method', 'include', 'class']"
                        )
                    line = f"{'%%'}{line}"
                    found_magic = True
                    break
            elif line.startswith("#|"):
                found_directive = True
            else:
                if found_directive:
                    raise ValueError(
                        "Line with #@@, corresponding to magic line in notebook, not found after having found line with directive #|"
                    )
                else:
                    raise ValueError("Directive line not found at beginning of cell")
    if not found_magic:
        raise ValueError("Magic line not found at beginning of cell")
    cell.source = "\n".join([line] + source_lines[line_number + 1 :])


# %% ../nbs/export.ipynb 57
def nbm_update(
    path: str | Path,
    code_cells_path: str | Path = ".nbmodular",
    logger_name: str = "nbmodular",
    log_level: str = "INFO",
):
    nb_processor = Bunch()
    path = Path(path)

    nb_processor.logger = create_or_get_logger(logger_name, log_level)
    set_paths_nb_processor(nb_processor, path, code_cells_path=code_cells_path)

    # prior to step 5 in diagram:
    # nbs/nb.ipynb => nbs/_nb.ipynb
    if nb_processor.dest_nb_path.exists():
        nb_processor.dest_nb_path.rename(nb_processor.duplicate_dest_nb_path)

    # step 5 in diagram:
    # .nbs/nb.ipynb => nbs/nb.ipynb
    if nb_processor.tmp_dest_nb_path.exists():
        nb_processor.tmp_dest_nb_path.rename(nb_processor.dest_nb_path)
    # .nbs/test_nb.ipynb => nbs/test_nb.ipynb
    if nb_processor.tmp_test_dest_nb_path.exists():
        nb_processor.tmp_test_dest_nb_path.rename(nb_processor.test_dest_nb_path)

    # step 5 in diagram: nbdev_update
    # import pdb
    # pdb.set_trace()
    if nb_processor.dest_python_path.exists():
        _update_mod(
            nb_processor.dest_python_path,
            lib_dir=Path(nb_processor.lib_path).parent.resolve(),
        )
    else:
        nb_processor.logger.info(
            f"No python file to update {nb_processor.dest_python_path}"
        )
    if nb_processor.test_dest_python_path.exists():
        _update_mod(
            nb_processor.test_dest_python_path,
            lib_dir=Path(nb_processor.lib_path).parent.resolve(),
        )
    else:
        nb_processor.logger.info(
            f"No test python file to update {nb_processor.test_dest_python_path}"
        )

    # obtain cell types and read them from notebooks
    nb_processor.cell_types = joblib.load(nb_processor.cell_types_file_path)
    original_nb = read_nb(path)
    if nb_processor.dest_nb_path.exists():
        dest_nb = read_nb(nb_processor.dest_nb_path)
    else:
        nb_processor.logger.info(f"File {nb_processor.dest_nb_path} not found")
    if nb_processor.test_dest_nb_path.exists():
        test_dest_nb = read_nb(nb_processor.test_dest_nb_path)
    else:
        nb_processor.logger.info(f"File {nb_processor.test_dest_nb_path} not found")
    nb_processor.cells = []
    code_idx, test_idx = 1, 1
    for original_idx, cell_type in enumerate(nb_processor.cell_types):
        cell = None
        original_cell = original_nb.cells[original_idx]
        if cell_type == "original":
            cell = original_cell
        elif cell_type == "code":
            cell = dest_nb.cells[code_idx]
            cell["outputs"] = original_cell["outputs"]
            code_idx += 1
        elif cell_type == "test":
            cell = test_dest_nb.cells[test_idx]
            cell["outputs"] = original_cell["outputs"]
            test_idx += 1
        if cell is not None:
            if cell_type in ["code", "test"]:
                process_cell_for_nbm_update(cell)
            nb_processor.cells.append(cell)

    original_nb.cells = nb_processor.cells
    write_nb(original_nb, path)


# %% ../nbs/export.ipynb 69
def nbm_update_all_paths(path: str | Path):
    config = get_config()
    # To test:
    # original_path = Path(path)
    # nbm_folder = config["nbm_path"]
    # if nbm_folder not in original_path.parts and (original_path / nbm_folder).exists:
    #     path = str (original_path / nbm_folder)
    files = nbglob(path=path, as_path=True).sorted("name")
    for f in files:
        nbm_update(f)


def parse_argv_and_run_nbm_update_all_paths(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Udpdate python modules from their corresponding notebooks."
    )

    parser.add_argument("--path", type=str, default=None, help="Path to python module")
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.path is None:
        args.path = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Importing python modules to path: {args.path}")
    nbm_update_all_paths(args.path)


def nbm_update_cli():
    parse_argv_and_run_nbm_update_all_paths(sys.argv[1:])
