# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/jupynbm.ipynb.

# %% auto 0
__all__ = [
    "jupynbm",
    "parse_argv_and_run_jupynbm",
    "jupynbm_export_cli",
    "nbmjupy",
    "parse_argv_and_run_nbmjupy",
    "nbmjupy_import_cli",
]

# %% ../nbs/jupynbm.ipynb 2
# Standard
import argparse
from logging import warn
import sys
import shutil
from pathlib import Path
from typing import List, Tuple
import os
import glob
import warnings

# 3rd party
from jupytext.cli import jupytext

# nbmodular
from .export import nbm_export_all_paths, nbm_update_all_paths
from .utils import create_or_get_logger, get_config


# %%
# Standard
import os
from pathlib import Path
import logging

# 3rd party
from nbdev.processors import Processor, NBProcessor
from execnb.nbio import read_nb, write_nb


def is_jupytext_header(text: str) -> bool:
    """Determine if the jupytext header has been written at beginning of notebook."""
    lines = text.split("\n")
    detected_starting_comment = False
    detected_jupyter_header = False
    in_jupyter_section = False

    for i, line in enumerate(lines):
        if line.strip() == "# ---" and not detected_starting_comment:
            detected_starting_comment = True
        if line.strip() == "# jupyter:" and detected_starting_comment:
            in_jupyter_section = True
            continue
        if line.strip() == "# ---" and in_jupyter_section:
            detected_jupyter_header = True
            break

    return detected_jupyter_header


class NbFilterer(Processor):
    """
    Processor class for exporting notebooks with magic commands.

    Parameters:
    ----------
    path : str
        The path to the notebook file.
    nb : fastcore.basics.AttrDict, optional
        The notebook object. If not provided, it will be read from the file specified by `path`.
    code_cells_file_name : str, optional
        The name of the file to store the code cells. If not provided, it will be set to the file name without extension.
    code_cells_path : str, optional
        The path to the directory where the code cells file will be stored. Default is ".nbmodular".
    execute : bool, optional
        Flag indicating whether to execute the notebook before exporting. Default is True.
    logger : logging.Logger, optional
        The logger object to use for logging. If not provided, a new logger will be created.
    log_level : str, optional
        The log level for the logger. Default is "INFO".
    tab_size : int, optional
        The number of spaces to use for indentation. Default is 4.
    """

    def __init__(
        self,
        path,
        nb=None,
    ):
        nb = read_nb(path) if nb is None else nb
        self.path = path
        super().__init__(nb)
        self.in_first_cell = True

    def cell(self, cell):
        """
        Process a cell.

        Parameters:
        ----------
        cell : nbdev.NbCell
            The cell to process.
        """

        # Filter specific for jupytext translated notebooks
        if self.in_first_cell:
            self.in_first_cell = False
            if cell.cell_type == "code" and is_jupytext_header(cell.source):
                nb = self.nb.copy()
                nb.cells = self.nb.cells[1:]
                write_nb(nb, self.path)


def nbm_filtering(
    path,
    **kwargs,
):
    """ """
    path = Path(path)
    nb = read_nb(path)
    processor = NbFilterer(
        path,
        nb=nb,
        **kwargs,
    )
    NBProcessor(path, processor, rm_directives=False, nb=nb).process()


def update_jupytext_notebooks(jupytext_path: str, extension: str) -> None:
    """update the notebooks in jupytext_path"""
    for root, dirs, files in os.walk(jupytext_path):
        current_path = os.getcwd()
        os.chdir(root)
        Path("./jupytext.toml").write_text(
            'formats = "ipynb,py:percent"\ncomment_magics=false\n'
        )
        jupytext(
            f"--set-formats ipynb,py:percent --format-options comment_magics=false *{extension}".split()
        )
        # nb_paths = glob.glob ("*.ipynb")
        # for nb_path in nb_paths:
        #     nbm_filtering (nb_path)
        os.chdir(current_path)


def sync_nbm_and_jupytext(jupytext_path: str, nbm_path: str, extension: str) -> None:
    """Update notebooks from nbm to jupytext"""
    # move notebooks to jupytext_path
    migrate_files(nbm_path, jupytext_path, ".ipynb", ".py")

    # update the notebooks in jupytext_path
    update_jupytext_notebooks(jupytext_path, extension=extension)

    # move updated notebooks to nbm_path
    migrate_files(jupytext_path, nbm_path, ".ipynb", ".py")


# %% ../nbs/jupynbm.ipynb 4
def jupynbm(
    jupytext_path: str,
    nbm_path: str,
    from_notebook: bool = False,
    restrict_inputs: bool = False,
) -> None:
    """
    Export jupytext modules to nbmodular notebooks
    """
    # update the notebooks in jupytext_path: nbm_path => jupytext_path
    sync_nbm_and_jupytext(jupytext_path, nbm_path, extension=".py")

    # update:
    # - the doc files: nbm_path => nbs_path
    # - the py files: nbm_path => lib_path
    if not from_notebook:
        restrict_inputs = True
    nbm_export_all_paths(
        nbm_path, from_notebook=from_notebook, restrict_inputs=restrict_inputs
    )


def parse_argv_and_run_jupynbm(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Udpdate python modules from their corresponding notebooks."
    )

    parser.add_argument(
        "--jupytext",
        type=str,
        default=None,
        help="Path to jupytext modules",
    )
    parser.add_argument(
        "--nbm",
        type=str,
        default=None,
        help="Path to nbmodular notebooks",
    )
    parser.add_argument(
        "--restrict-inputs",
        action="store_true",
        default=None,
        help="Restrict inputs to only those specified",
    )
    parser.add_argument(
        "--from-notebook",
        action="store_true",
        default=None,
        help="Indicate that the operation is from a notebook",
    )
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.jupytext is None:
        args.jupytext = str(Path(get_config()["jupy_path"]).resolve())
    if args.nbm is None:
        args.nbm = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Exporting jupytext python modules from {args.jupytext} to {args.nbm}")
    jupynbm(
        args.jupytext,
        args.nbm,
        from_notebook=args.from_notebook,
        restrict_inputs=args.restrict_inputs,
    )


def jupynbm_export_cli():
    parse_argv_and_run_jupynbm(sys.argv[1:])


def srcpaths_in_dst(
    src_mfe_files: List[Path],
    src_path: str,
    dst_path: str,
    alternative_suffix: str,
) -> Tuple[List[Path], List[Path]]:

    dst_mfe_files = []
    dst_ae_files = []
    for src_mfe_file in src_mfe_files:
        dst_relative_path = src_mfe_file.relative_to(src_path)
        dst_mfe_file = Path(dst_path) / dst_relative_path
        dst_mfe_files.append(dst_mfe_file)
        dst_ae_file = dst_mfe_file.with_suffix(f"{alternative_suffix}")
        dst_ae_files.append(dst_ae_file)
    return dst_mfe_files, dst_ae_files


def rename_mfe_files(src_mfe_files, dst_mfe_files, dst_ae_files):
    for dst_ae_file, dst_mfe_file, src_mfe_file in zip(
        dst_ae_files, dst_mfe_files, src_mfe_files
    ):
        if not dst_ae_file.exists():
            warnings.warn(f"{dst_ae_file} does not exist, but {src_mfe_file} does.")
            dst_mfe_file.parent.mkdir(parents=True, exist_ok=True)
        src_mfe_file.rename(dst_mfe_file)


def migrate_files(src_path, dst_path, mf_suffix, alternative_suffix):
    """
    src can be nbm_path
    dst can be jupytext_path
    mf_suffix can be .ipynb
    alternative_suffix can be .py

    Parameters
    ----------
    src_path : _type_
        _description_
    dst_path : _type_
        _description_
    mf_suffix : _type_
        _description_
    alternative_suffix : _type_
        _description_
    """
    # gather updated list of notebook files
    src_mfe_files = list(Path(src_path).rglob(f"*{mf_suffix}"))
    dst_mfe_files = list(Path(dst_path).rglob(f"*{mf_suffix}"))
    if len(dst_mfe_files) > 0:
        raise FileExistsError(
            f"There are already files with extension {mf_suffix} in the destination path"
        )

    # generate corresponding file in dst_path
    dst_mfe_files, dst_ae_files = srcpaths_in_dst(
        src_mfe_files, src_path, dst_path, alternative_suffix
    )

    # move src mfe files to their corresponding folders in dst_path
    rename_mfe_files(src_mfe_files, dst_mfe_files, dst_ae_files)


# %% ../nbs/jupynbm.ipynb 6
def nbmjupy(nbm_path: str, jupytext_path: str) -> None:
    """
    nbm notebooks to jupytext .py files

    Moves the notebooks .ipynb to jupytext_path before converting to .py
    """

    # update the notebooks in nbm_path: lib_path => nbm_path
    nbm_update_all_paths(nbm_path)

    # update the notebooks in nbm_path: jupytext_path => nbm_path
    sync_nbm_and_jupytext(jupytext_path, nbm_path, extension=".ipynb")


def parse_argv_and_run_nbmjupy(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Udpdate python modules from their corresponding notebooks."
    )

    parser.add_argument(
        "--nbm",
        type=str,
        default=None,
        help="Path to nbmodular notebooks",
    )
    parser.add_argument(
        "--jupytext",
        type=str,
        default=None,
        help="Path to jupytext modules",
    )
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.jupytext is None:
        args.jupytext = str(Path(get_config()["jupy_path"]).resolve())
    if args.nbm is None:
        args.nbm = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Exporting nbm notebooks from {args.nbm} to {args.jupytext}")
    nbmjupy(args.nbm, args.jupytext)


def nbmjupy_import_cli():
    parse_argv_and_run_nbmjupy(sys.argv[1:])
