# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/jupynbm.ipynb.

# %% auto 0
__all__ = [
    "jupynbm",
    "parse_argv_and_run_jupynbm",
    "jupynbm_export_cli",
    "nbmjupy",
    "parse_argv_and_run_nbmjupy",
    "nbmjupy_import_cli",
]

# %% ../nbs/jupynbm.ipynb 2
# Standard
import argparse
from logging import warn
import sys
import shutil
from pathlib import Path
from typing import List, Tuple
import os
import glob
import warnings

# 3rd party
from jupytext.cli import jupytext

# nbmodular
from .export import nbm_export_all_paths, nbm_update_all_paths
from .utils import create_or_get_logger, get_config


# %%
def update_jupytext_notebooks(jupytext_path: str, extension: str) -> None:
    """update the notebooks in jupytext_path"""
    for root, dirs, files in os.walk(jupytext_path):
        current_path = os.getcwd()
        os.chdir(root)
        jupytext(
            f"--set-formats ipynb,py:percent --format-options comment_magics=false *{extension}".split()
        )
        os.chdir(current_path)


def sync_nbm_and_jupytext(jupytext_path: str, nbm_path: str, extension: str) -> None:
    """Update notebooks from nbm to jupytext"""
    # move notebooks to jupytext_path
    migrate_files(nbm_path, jupytext_path, ".ipynb", ".py")

    # update the notebooks in jupytext_path
    update_jupytext_notebooks(jupytext_path, extension=extension)

    # move updated notebooks to nbm_path
    migrate_files(jupytext_path, nbm_path, ".ipynb", ".py")


# %% ../nbs/jupynbm.ipynb 4
def jupynbm(jupytext_path: str, nbm_path: str) -> None:
    """
    Export jupytext modules to nbmodular notebooks
    """
    # update the notebooks in jupytext_path: nbm_path => jupytext_path
    sync_nbm_and_jupytext(jupytext_path, nbm_path, extension=".py")

    # update:
    # - the doc files: nbm_path => nbs_path
    # - the py files: nbm_path => lib_path
    nbm_export_all_paths(nbm_path)


def parse_argv_and_run_jupynbm(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Udpdate python modules from their corresponding notebooks."
    )

    parser.add_argument(
        "--jupytext",
        type=str,
        default=None,
        help="Path to jupytext modules",
    )
    parser.add_argument(
        "--nbm",
        type=str,
        default=None,
        help="Path to nbmodular notebooks",
    )
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.jupytext is None:
        args.jupytext = str(Path(get_config()["jupy_path"]).resolve())
    if args.nbm is None:
        args.nbm = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Exporting jupytext python modules from {args.jupytext} to {args.nbm}")
    jupynbm(args.jupytext, args.nbm)


def jupynbm_export_cli():
    parse_argv_and_run_jupynbm(sys.argv[1:])


def srcpaths_in_dst(
    src_mfe_files: List[Path],
    src_path: str,
    dst_path: str,
    alternative_suffix: str,
) -> Tuple[List[Path], List[Path]]:

    dst_mfe_files = []
    dst_ae_files = []
    for src_mfe_file in src_mfe_files:
        dst_relative_path = src_mfe_file.relative_to(src_path)
        dst_mfe_file = Path(dst_path) / dst_relative_path
        dst_mfe_files.append(dst_mfe_file)
        dst_ae_file = dst_mfe_file.with_suffix(f"{alternative_suffix}")
        dst_ae_files.append(dst_ae_file)
    return dst_mfe_files, dst_ae_files


def rename_mfe_files(src_mfe_files, dst_mfe_files, dst_ae_files):
    for dst_ae_file, dst_mfe_file, src_mfe_file in zip(
        dst_ae_files, dst_mfe_files, src_mfe_files
    ):
        if not dst_ae_file.exists():
            warnings.warn(f"{dst_ae_file} does not exist, but {src_mfe_file} does.")
            dst_mfe_file.parent.mkdir(parents=True, exist_ok=True)
        src_mfe_file.rename(dst_mfe_file)


def migrate_files(src_path, dst_path, mf_suffix, alternative_suffix):
    """
    src can be nbm_path
    dst can be jupytext_path
    mf_suffix can be .ipynb
    alternative_suffix can be .py

    Parameters
    ----------
    src_path : _type_
        _description_
    dst_path : _type_
        _description_
    mf_suffix : _type_
        _description_
    alternative_suffix : _type_
        _description_
    """
    # gather updated list of notebook files
    src_mfe_files = list(Path(src_path).rglob(f"*{mf_suffix}"))
    dst_mfe_files = list(Path(dst_path).rglob(f"*{mf_suffix}"))
    if len(dst_mfe_files) > 0:
        raise FileExistsError(
            f"There are already files with extension {mf_suffix} in the destination path"
        )

    # generate corresponding file in dst_path
    dst_mfe_files, dst_ae_files = srcpaths_in_dst(
        src_mfe_files, src_path, dst_path, alternative_suffix
    )

    # move src mfe files to their corresponding folders in dst_path
    rename_mfe_files(src_mfe_files, dst_mfe_files, dst_ae_files)


# %% ../nbs/jupynbm.ipynb 6
def nbmjupy(nbm_path: str, jupytext_path: str) -> None:
    """
    nbm notebooks to jupytext .py files

    Moves the notebooks .ipynb to jupytext_path before converting to .py
    """

    # update the notebooks in nbm_path: lib_path => nbm_path
    nbm_update_all_paths(nbm_path)

    # update the notebooks in nbm_path: jupytext_path => nbm_path
    sync_nbm_and_jupytext(jupytext_path, nbm_path, extension=".ipynb")


def parse_argv_and_run_nbmjupy(argv: List[str]):
    parser = argparse.ArgumentParser(
        description="Udpdate python modules from their corresponding notebooks."
    )

    parser.add_argument(
        "--nbm",
        type=str,
        default=None,
        help="Path to nbmodular notebooks",
    )
    parser.add_argument(
        "--jupytext",
        type=str,
        default=None,
        help="Path to jupytext modules",
    )
    args = parser.parse_args(argv)
    logger = create_or_get_logger()
    if args.jupytext is None:
        args.jupytext = str(Path(get_config()["jupy_path"]).resolve())
    if args.nbm is None:
        args.nbm = str(Path(get_config()["nbm_path"]).resolve())
    logger.info(f"Exporting nbm notebooks from {args.nbm} to {args.jupytext}")
    nbmjupy(args.nbm, args.jupytext)


def nbmjupy_import_cli():
    parse_argv_and_run_nbmjupy(sys.argv[1:])
