# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/test_utils.ipynb.

# %% auto 0
__all__ = [
    "nb1",
    "mixed_nb1",
    "complete_nb1",
    "py1",
    "convert_nested_nb_cells_to_dicts",
    "parse_nb_sections",
    "text2nb",
    "texts2nbs",
    "nb2text",
    "nbs2text",
    "printnb",
    "strip_nb",
    "read_nbs_in_repo",
    "read_pymodules_in_repo",
    "read_cell_types_lists",
    "read_cell_types_lists_in_repo",
    "read_content_in_repo",
    "derive_nb_paths",
    "derive_py_paths",
    "derive_cell_types_paths",
    "derive_all_paths",
    "read_nbs",
    "compare_nb",
    "compare_nbs",
    "read_text_files",
    "write_text_files",
    "compare_texts",
    "print_files",
    "read_and_print",
    "check_nbs",
    "check_py_modules",
    "check_test_repo_content",
    "create_and_cd_to_new_root_folder",
    "create_test_content",
]

# %% ../nbs/test_utils.ipynb 2
# standard
import logging
import os
import shutil
from pathlib import Path
from token import OP
from typing import List, Tuple, Optional, Union, Dict
import re

# 3rd party
from execnb.nbio import new_nb, write_nb, mk_cell, read_nb, NbCell
from nbdev.doclinks import nbglob
from fastcore.basics import AttrDict
import joblib

# ours
from .utils import cd_root, create_or_get_logger, get_config

# %% ../nbs/test_utils.ipynb 5
nb1 = """
[markdown]
# First notebook

[code]
%%function hello
print ('hello')

[code]
%%function one_plus_one --test
a=1+1
print (a)
"""

# %% ../nbs/test_utils.ipynb 9
mixed_nb1 = """
[code]
%%function
def first():
    pass

[markdown]
comment
    
[code]
%%function --test
def second ():
    pass
"""

complete_nb1 = """
[markdown]
# core

> Fill in a module description here

[code]
%load_ext nbmodular.cell2func

[code]
%%function
def foo():
    print("hello")

[code]
foo()

[code]
x = 3
y = 5

[code]
%%function
def f (x, y):
    z = x + y
    return z

[code]
z

[code]
%%function
def g (z):
    r = z * 2
    print (f"r = {r}")
    return r
"""

real_nb1 = """
[code]
['add_100_info.previous_variables']
<output>
[('two_plus_three',
  "#|echo: false\na = 2\nb = 3\nc = a+b\nprint (f'The result of adding {a}+{b} is {c}')\n"),
 ('add_100',
  "#|echo: false\nmy_previous_variable = my_previous_variable + 100\nprint (f'The result of adding 100 to my_previous_variable is {my_previous_variable}')\n"),
 ('add_100',
  "#|echo: false\nmy_previous_variable = my_previous_variable + 100\nprint (f'The result of adding 100 to my_previous_variable is {my_previous_variable}')\n"),
 ('hybrid', 'x = 3\nx = x + 4\nprint (x)\n'),
 ('hybrid', 'x = 3\nx = x + 4\nprint (x)\n'),
 ('multiply_by_two',
  "#|echo: false\nd = c*2\nprint (f'Two times {c} is {d}')\n"),
 ('get_my_previous_variable --position 0',
  '#| echo: false\nmy_previous_variable = 100\n'),
 ('add_100 --include-output my_previous_variable',
  "#| echo: false\nmy_previous_variable = my_previous_variable + 100\nprint (f'The result of adding 100 to my_previous_variable is {my_previous_variable}')\n")]

[markdown]
['`my_previous_variable` is also included in the list of `created_variables`, since a new value for this variable has been generated:']

[code]
['%set default_write True\n', '%set default_test_write True']
"""

# %% ../nbs/test_utils.ipynb 12
py1 = """
def hello ():
    print ('hello')

def one_plus_one ():
    a=1+1
    print (a)
"""


# %% ../nbs/test_utils.ipynb 22
def convert_nested_nb_cells_to_dicts(dict_like_with_nbcells: dict) -> dict:
    """Convert nested NbCells to dicts.

    Parameters
    ----------
    dict_like_with_nbcells : dict
        dict-like object with embedded NbCell cells

    Returns
    -------
    dict
        dict object without embedded NbCell cells
    """
    new_dict = {k: v for k, v in dict_like_with_nbcells.items()}
    new_dict["cells"] = [dict(**cell) for cell in new_dict["cells"]]
    return new_dict


# %% ../nbs/test_utils.ipynb 24
def parse_nb_sections(nb):
    # Define the regex pattern to match sections
    pattern = "\[(markdown|code)\](.*?)((?=\[markdown\])|(?=\[code\])|$)"

    # Find all matches using re.findall which returns a list of tuples
    matches = re.findall(pattern, nb, re.DOTALL)

    # Transform the matches to the required format
    result = [(match[0], match[1].strip()) for match in matches]
    result_with_output = []
    for cell_type, content in result:
        kwargs["metadata"] = {}
        if cell_type == "code":
            output_match = re.search(r"<output>(.*)", content, re.DOTALL)
            if output_match:
                content, output = (
                    content[: output_match.start()],
                    output_match.group(1),
                )
                kwargs["outputs"] = [output]
            else:
                kwargs["outputs"] = []
            kwargs["execution_count"] = 0
        result_with_output.append((cell_type, content, kwargs))

    return result_with_output


# %% ../nbs/test_utils.ipynb 28
def text2nb(nb: str) -> dict | AttrDict:
    cells = [
        # mk_cell(text, cell_type=cell_type) for cell_type, text in parse_nb_sections(nb)
        NbCell(0, dict(cell_type=cell_type, source=text, directives_={}, **kwargs))
        for cell_type, text, kwargs in parse_nb_sections(nb)
    ]
    return new_nb(cells)  # type: ignore


# %% ../nbs/test_utils.ipynb 34
def texts2nbs(nbs: List[str] | str) -> List[dict]:
    if not isinstance(nbs, list):
        nbs = [nbs]
    return [text2nb(nb) for nb in nbs]


# %% ../nbs/test_utils.ipynb 36
def nb2text(nb: dict) -> str:
    return "\n\n".join(
        [f"[{cell['cell_type']}]\n{cell['source']}" for cell in nb["cells"]]
    )


def nb2text_with_output(nb: dict) -> str:
    output_cells = []
    for cell in nb["cells"]:
        if (
            "outputs" in cell
            and len(cell["outputs"]) > 0
            and "data" in cell["outputs"][0]
            and "text/plain" in cell["outputs"][0]["data"]
        ):
            output = "".join(cell["outputs"][0]["data"]["text/plain"])
            output_cells.append(
                f"[{cell['cell_type']}]\n{cell['source']}\n<output>\n{output}"
            )
        else:
            output_cells.append(f"[{cell['cell_type']}]\n{cell['source']}")
    return "\n\n".join(output_cells)


def nbs2text(nbs: List[dict]) -> List[str]:
    return [nb2text(nb) for nb in (nbs if isinstance(nbs, list) else [nbs])]


# %% ../nbs/test_utils.ipynb 42
def printnb(
    nb_text: str | dict | List[str] | List[dict], no_newlines: bool = False, titles=None
) -> None:
    if isinstance(nb_text, list):
        assert titles is None or len(titles) == len(nb_text)
        titles = (
            ["\n"] * len(nb_text)
            if titles is None
            else ["\n" + title for title in titles]
        )
        for nb_text, title in zip(nb_text, titles):
            print(title)
            print(f"{'-'*50}")
            printnb(nb_text, no_newlines=no_newlines)
    else:
        if isinstance(nb_text, dict):
            nb_text = nb2text(nb_text)
        print(f'''"""{nb_text}"""''' if no_newlines else f'''"""\n{nb_text}\n"""''')


# %% ../nbs/test_utils.ipynb 48
def strip_nb(nb: str) -> str:
    return nb2text(text2nb(nb))


# %% ../nbs/test_utils.ipynb 50
def read_nbs_in_repo(
    nb_paths: Optional[List[str]] = None,  # type: ignore
    new_root: Optional[str] = ".",
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
    use_config_paths: bool = True,
    print_as_list: bool = False,
    display: bool = False,
    logger: logging.Logger = None,
    logger_name: str = "nbmodular",
    previous_text: str = "",
    posterior_text: str = "",
):
    """
    Read notebooks in a repository.

    Parameters
    ----------
    nb_paths : List[str]
        List of notebook paths.
    new_root : str, optional
        New root directory, by default "new_test".
    nbm_folder : str, optional
        Folder name for nbm, by default "nbm".
    tmp_folder : str, optional
        Temporary folder name, by default ".nbs".
    nbs_folder : str, optional
        Folder name for nbs, by default "nbs".
    print_as_list : bool, optional
        Whether to print the files as a list, by default False.
    print : bool, optional
        Whether to print the files, by default False.
    previous_text : str, optional
        Text to print before the files, by default "".
    posterior_text : str, optional
        Text to print after the files, by default "".

    Returns
    -------
    content : dict
        Dictionary containing the content of the notebooks.
    """
    logger = create_or_get_logger(logger_name)
    if use_config_paths:
        config = get_config()
        if nbm_folder is None:
            nbm_folder = config["nbm_path"]
        if nbs_folder is None:
            nbs_folder = config["nbs_path"]
    if nb_paths is None and nbm_folder is not None:
        nb_paths = nbglob(path=nbm_folder, as_path=True).sorted("name")  # type: ignore
        # Remove the nbm_folder part from the paths, unless the nbm_folder is "."
        if Path(".").resolve() != Path(nbm_folder).resolve():
            nb_paths = [Path(*x.parts[1:]) for x in nb_paths]
    elif not isinstance(nb_paths, list):
        nb_paths = [nb_paths]  # type: ignore
    if new_root is not None and not Path(new_root).exists():
        logger.warning(f"{new_root} does not exist. Replacing it with '.'")
        new_root = "."
    if new_root is None:
        new_root = "."
    if nbm_folder is not None and not (Path(new_root) / nbm_folder).exists():
        raise FileNotFoundError(f"{nbm_folder} does not exist in {new_root}")
    if nbs_folder is not None and not (Path(new_root) / nbs_folder).exists():
        raise FileNotFoundError(f"{nbs_folder} does not exist in {new_root}")
    nb_paths: List[Path] = derive_nb_paths(
        nb_paths,  # type: ignore
        new_root,
        nbm_folder=nbm_folder,
        tmp_folder=tmp_folder,
        nbs_folder=nbs_folder,
    )
    logger.debug(f"Reading notebooks in {nb_paths}")
    content, nb_paths = read_nbs(nb_paths)
    if display:
        print_files(
            content,
            print_as_list=print_as_list,
            paths=nb_paths,
            previous_text=previous_text,
            posterior_text=posterior_text,
        )
    return content, nb_paths


# %% ../nbs/test_utils.ipynb 52
def read_pymodules_in_repo(
    nb_paths: List[str],  # type: ignore
    new_root: str = "new_test",
    lib_folder: str = "nbmodular",
    print_as_list: bool = False,
    display: bool = False,
    previous_text: str = "",
    posterior_text: str = "",
    interactive_notebook: bool = True,
):
    """
    Read Python modules in a repository.

    Parameters:
    ----------
    nb_paths : List[str]
        List of paths to Jupyter notebooks.
    new_root : str, optional
        New root directory for the notebooks, by default "new_test".
    lib_folder : str, optional
        Name of the library folder, by default "nbmodular".
    print_as_list : bool, optional
        Whether to print the files as a list, by default False.
    print : bool, optional
        Whether to print the files, by default False.
    interactive_notebook : bool, optional
        Whether the notebook is run in VSC interactive mode, by default True.

    Returns:
    -------
    content : str
        Content of the Python modules.

    """
    py_paths = derive_py_paths(nb_paths, new_root, lib_folder=lib_folder)
    content, py_paths = read_text_files(py_paths)
    if interactive_notebook:
        content = [x.replace("%%", "@%%") for x in content]
    if display:
        print_files(
            content,
            print_as_list=print_as_list,
            paths=py_paths,
            previous_text=previous_text,
            posterior_text=posterior_text,
        )
    return content, py_paths


# %% ../nbs/test_utils.ipynb 54
def read_cell_types_lists(
    paths: List[str | Path], must_exist: Dict[str | Path, bool] = {}
) -> List[str]:
    """
    Read the contents of Python modules from the given paths.

    Parameters
    ----------
    paths : List[str]
        A list of file paths to Python modules.

    Returns
    -------
    List[str]
        A list of strings containing the contents of the Python modules.

    Raises
    ------
    AssertionError
        If a file path does not exist.

    """
    cell_types_lists = []
    paths = [Path(path) for path in paths]
    for path in paths:
        # Check that file exists. useful for being called inside a test utility
        # to see where it fails.
        if path.exists():
            cell_types_lists.append(joblib.load(path))
        elif must_exist.get(path, False):
            raise FileNotFoundError(f"File {path} does not exist")

    return cell_types_lists


# %% ../nbs/test_utils.ipynb 56
def read_cell_types_lists_in_repo(
    nb_paths: List[str],  # type: ignore
    new_root: str = "new_test",
    cell_types_folder: str = ".nbmodular",
    print_as_list: bool = False,
    tab_size: int = 4,
) -> List[List[str]]:
    """
    Read Python modules in a repository.

    Parameters:
    ----------
    nb_paths : List[str]
        List of paths to Jupyter notebooks.
    new_root : str, optional
        New root directory for the notebooks, by default "new_test".
    lib_folder : str, optional
        Name of the library folder, by default "nbmodular".
    print_as_list : bool, optional
        Whether to print the files as a list, by default False.
    print : bool, optional
        Whether to print the files, by default False.
    interactive_notebook : bool, optional
        Whether the notebook is run in VSC interactive mode, by default True.

    Returns:
    -------
    content : str
        Content of the Python modules.

    """
    cell_types_paths = derive_cell_types_paths(
        nb_paths, new_root, cell_types_folder=cell_types_folder
    )
    cell_types_lists = read_cell_types_lists(cell_types_paths)

    if print_as_list:
        print("cell_types_lists = [")
        for x in cell_types_lists:
            print(f"{' '*tab_size}{x},")
        print("]")
        print(f"cell_types_paths={cell_types_paths}")
    return cell_types_lists


# %% ../nbs/test_utils.ipynb 58
def read_content_in_repo(
    nb_paths: Optional[List[str]] = None,
    new_root: Union[str, Path] = ".",
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
    lib_folder: Optional[str] = "nbmodular",
    cell_types_folder: Optional[str] = ".nbmodular",
    print_as_list: bool = False,
    display: bool = True,
    interactive_notebook: bool = True,
):
    """
    Read the content in a repository.

    Parameters:
    ----------
    nb_paths : List[str]
        List of notebook paths.
    new_root : Union[str, Path]
        New root directory.
    nbm_folder : str, optional
        Folder name for nbm files. Defaults to "nbm".
    tmp_folder : str, optional
        Temporary folder name. Defaults to ".nbs".
    nbs_folder : str, optional
        Folder name for nbs files. Defaults to "nbs".
    lib_folder : str, optional
        Folder name for nbmodular files. Defaults to "nbmodular".
    print_as_list : bool, optional
        Whether to print the content as a list. Defaults to False.
    print : bool, optional
        Whether to print the content. Defaults to True.

    Returns:
    -------
    Tuple[List[str], List[str]]
        A tuple containing two lists - the nbs content and the py_modules content.
    """
    if interactive_notebook and not print_as_list:
        raise ValueError(
            "interactive_notebook can only be True if print_as_list is True"
        )
    if print_as_list:
        previous_text = "expected_nbs = "
    nbs, existing_nb_paths = read_nbs_in_repo(
        nb_paths,
        new_root,
        nbm_folder,
        tmp_folder,
        nbs_folder,
        print_as_list,
        display,
        previous_text=previous_text,
    )
    if print_as_list:
        print(f"existing_nb_paths={existing_nb_paths}")

    if print_as_list:
        previous_text = "expected_py_modules = "
    py_modules, existing_py_paths = (
        read_pymodules_in_repo(
            nb_paths,
            new_root,
            lib_folder,
            print_as_list,
            display,
            previous_text=previous_text,
            interactive_notebook=interactive_notebook,
        )
        if lib_folder is not None
        else []
    )

    if print_as_list:
        print(f"existing_py_paths={existing_py_paths}")

    cell_types_lists = (
        read_cell_types_lists_in_repo(
            nb_paths,
            new_root,
            cell_types_folder,
            print_as_list,
        )
        if cell_types_folder is not None
        else []
    )

    return nbs, existing_nb_paths, py_modules, existing_py_paths, cell_types_lists


# %% ../nbs/test_utils.ipynb 61
from typing import List, Optional
from pathlib import Path


def derive_nb_paths(
    nb_paths: List[str],
    new_root: str | Path,
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
) -> List[Path]:
    """
    Derives the paths of notebooks based on the given parameters.

    Parameters
    ----------
    nb_paths : List[str]
        A list of notebook paths.
    new_root : str | Path
        The new root directory where the notebooks will be located.
    nbm_folder : Optional[str], optional
        The folder name for nbm files. Defaults to "nbm".
    tmp_folder : Optional[str], optional
        The temporary folder name. Defaults to ".nbs".
    nbs_folder : Optional[str], optional
        The folder name for nbs files. Defaults to "nbs".

    Returns
    -------
    List[Path]
        A list of derived notebook paths.
    """
    all_nb_paths = []
    for nb_path in nb_paths:
        if Path(nb_path).is_absolute():
            all_nb_paths.append(Path(nb_path))
        else:
            if nbm_folder is not None:
                all_nb_paths.append(Path(new_root) / nbm_folder / nb_path)
            if nbs_folder is not None:
                nb_code_path = Path(new_root) / nbs_folder / nb_path
                all_nb_paths.append(nb_code_path)
                nb_test_path = nb_code_path.parent / f"test_{nb_code_path.name}"
                all_nb_paths.append(nb_test_path)
            if tmp_folder is not None:
                tmp_nb = Path(new_root) / tmp_folder / nb_path
                all_nb_paths.append(tmp_nb)
                tmp_test_nb = tmp_nb.parent / f"test_{tmp_nb.name}"
                all_nb_paths.append(tmp_test_nb)

    return all_nb_paths


# %% ../nbs/test_utils.ipynb 63
def derive_py_paths(
    nb_paths: List[str],
    new_root: str | Path,
    lib_folder: str = "nbmodular",
):
    py_paths = []
    for nb_path in nb_paths:
        original_nb_path = Path(nb_path)
        py_paths.append(
            Path(new_root)
            / lib_folder
            / original_nb_path.parent
            / f"{original_nb_path.stem}.py"
        )
        py_paths.append(
            Path(new_root)
            / lib_folder
            / "tests"
            / original_nb_path.parent
            / f"test_{original_nb_path.stem}.py"
        )
    return py_paths


# %% ../nbs/test_utils.ipynb 65
def derive_cell_types_paths(
    nb_paths: List[str],
    new_root: str | Path,
    cell_types_folder: str = ".nbmodular",
):
    cell_types_paths = []
    for nb_path in nb_paths:
        original_nb_path = Path(nb_path)
        cell_types_paths.append(
            Path(new_root)
            / cell_types_folder
            / original_nb_path.parent
            / f"cell_types_{original_nb_path.stem}.pk"
        )
    return cell_types_paths


# %% ../nbs/test_utils.ipynb 67
def derive_all_paths(
    nb_paths: List[str],
    new_root: str | Path,
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
    lib_folder: Optional[str] = "nbmodular",
    cell_types_folder: Optional[str] = ".nbmodular",
):
    all_nb_paths = derive_nb_paths(
        nb_paths,
        new_root,
        nbm_folder=nbm_folder,
        tmp_folder=tmp_folder,
        nbs_folder=nbs_folder,
    )
    py_paths = (
        derive_py_paths(nb_paths, new_root, lib_folder=lib_folder)
        if lib_folder is not None
        else []
    )
    cell_types_paths = (
        derive_cell_types_paths(nb_paths, new_root, cell_types_folder=cell_types_folder)
        if cell_types_folder is not None
        else []
    )
    return all_nb_paths, py_paths, cell_types_paths


# %% ../nbs/test_utils.ipynb 71
def read_nbs(
    paths: List[str] | List[Path],
    must_exist: dict = {},
    as_text: bool = True,
) -> Tuple[List[str] | List[dict], List[Path]]:
    """
    Read notebooks from disk.

    Parameters:
        paths (List[str]): A list of paths to the notebooks.
        as_text (bool, optional): If True, the notebooks will be returned as text.
            If False, the notebooks will be returned as dictionaries.
            Defaults to True.

    Returns:
        List[str] | List[dict]: A list of notebooks. If `as_text` is True, the notebooks
            will be returned as text. If `as_text` is False, the notebooks will be
            returned as dictionaries.
    """
    nbs_in_disk = []
    paths = [Path(path) for path in paths]
    existing_paths = []
    for path in paths:
        # Check that file exists. useful for being called inside a test utility
        # to see where it fails.
        if path.exists():
            nbs_in_disk.append(read_nb(path))
            existing_paths.append(path)
        elif must_exist.get(path, False):
            raise FileNotFoundError(f"File {path} does not exist")

    return (
        [strip_nb(nb2text(nb)) for nb in nbs_in_disk] if as_text else nbs_in_disk,
        existing_paths,
    )


# %% ../nbs/test_utils.ipynb 75
def compare_nb(nb1: str, nb2: str) -> bool:
    return strip_nb(nb1) == strip_nb(nb2)


def compare_nbs(nbs1: List[str], nbs2: List[str]) -> bool:
    return all(map(compare_nb, nbs1, nbs2))


# %% ../nbs/test_utils.ipynb 79
def read_text_files(
    paths: List[str | Path], must_exist: Dict[str | Path, bool] = {}
) -> List[str]:
    """
    Read the contents of Python modules from the given paths.

    Parameters
    ----------
    paths : List[str]
        A list of file paths to Python modules.

    Returns
    -------
    List[str]
        A list of strings containing the contents of the Python modules.

    Raises
    ------
    AssertionError
        If a file path does not exist.

    """
    text_files = []
    paths = [Path(path) for path in paths]
    existing_paths = []
    for path in paths:
        # Check that file exists. useful for being called inside a test utility
        # to see where it fails.
        if path.exists():
            text_files.append(path.read_text())
            existing_paths.append(path)
        elif must_exist.get(path, False):
            raise FileNotFoundError(f"File {path} does not exist")

    return text_files, existing_paths


# %% ../nbs/test_utils.ipynb 81
def write_text_files(texts: List[str], paths: List[str]) -> None:
    for text, path in zip(texts, paths):
        with open(path, "wt") as file:
            file.write(text)


# %% ../nbs/test_utils.ipynb 83
def compare_texts(texts1: List[str], texts2: List[str]) -> bool:
    return all(map(lambda x, y: x.strip() == y.strip(), texts1, texts2))


# %% ../nbs/test_utils.ipynb 88
def print_files(
    files: List[str],
    print_as_list: bool = False,
    paths: Optional[List[str] | List[Path]] = None,
    previous_text: str = "",
    posterior_text: str = "",
) -> None:
    print(previous_text, end="")
    if print_as_list:
        print("[")
    suffix_path = "# " if print_as_list else ""
    for idx, file in enumerate(files):
        if not print_as_list:
            print(f"{'-'*50}")
        if paths is not None:
            print(f"{suffix_path}{paths[idx]}")
        print('"""')
        print(file)
        print('"""', end="")
        if print_as_list and idx < (len(files) - 1):
            print(",")
        else:
            print()
    if print_as_list:
        print("]")
    print(posterior_text, end="")


# %% ../nbs/test_utils.ipynb 89
def read_and_print(
    paths: List[str] | str, file_type: Optional[str] = None, print_as_list: bool = False
) -> None:
    if not isinstance(paths, list):
        paths = [paths]
    if file_type is None:
        if all([x.endswith(".ipynb") for x in paths]):
            file_type = "notebook"
        elif all([x.endswith(".py") for x in paths]):
            file_type = "text"
        else:
            raise ValueError("file_type not provided and not inferrable from paths")
    if file_type == "notebook":
        files, paths = read_nbs(paths)
    elif file_type == "text":
        files, paths = read_text_files(paths)
    else:
        raise ValueError(f"file_type {file_type} not recognized")

    print_files(
        files, print_as_list=print_as_list, paths=None if not print_as_list else paths
    )


# %% ../nbs/test_utils.ipynb 92
def check_nbs(
    nb_paths: List[str],  # type: ignore
    expected: List[str],
    new_root: str,  # type: ignore
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
):
    """
    Check if the notebooks in the given paths match the expected notebooks.

    Parameters
    ----------
    nb_paths : List[str]
        List of paths to the notebooks to be checked.
    expected : List[str]
        List of paths to the expected notebooks.
    new_root : str
        The new root directory for the notebooks.
    nbm_folder : str, optional
        The folder name for the notebook metadata (default is "nbm").
    tmp_folder : str, optional
        The temporary folder name for storing intermediate files (default is ".nbs").
    nbs_folder : str, optional
        The folder name for the processed notebooks (default is "nbs").

    Raises
    ------
    AssertionError
        If the actual notebooks do not match the expected notebooks.

    """
    actual, _ = read_nbs_in_repo(
        nb_paths,
        new_root,
        nbm_folder=nbm_folder,
        tmp_folder=tmp_folder,
        nbs_folder=nbs_folder,
    )
    assert compare_nbs(actual, expected)


# %% ../nbs/test_utils.ipynb 94
def check_py_modules(
    nb_paths: List[str],  # type: ignore
    expected: List[str],
    new_root: str,  # type: ignore
    lib_folder: str = "nbmodular",
    interactive_notebook: bool = True,
):
    """
    Check if the Python modules in the given notebook paths match the expected modules.

    Parameters
    ----------
    nb_paths : List[str]
        List of paths to the notebooks.
    expected : List[str]
        List of expected Python modules.
    new_root : str
        The new root directory.
    lib_folder : str, optional
        The name of the library folder, by default "nbmodular".
    interactive_notebook: bool, optional
        Whether the notebook is run in VSC interactive mode, by default True.

    Raises
    ------
    AssertionError
        If the actual Python modules do not match the expected modules.
    """
    actual, _ = read_pymodules_in_repo(
        nb_paths,
        new_root,
        lib_folder=lib_folder,
        interactive_notebook=interactive_notebook,
    )
    assert compare_texts(actual, expected)


# %% ../nbs/test_utils.ipynb 96
def check_test_repo_content(
    nb_paths: List[str],
    expected_nbs: Optional[List[str]] = None,
    expected_py_modules: Optional[List[str]] = None,
    current_root: Optional[str] = None,
    new_root: Optional[str] = None,
    nbm_folder: Optional[str] = "nbm",
    tmp_folder: Optional[str] = ".nbs",
    nbs_folder: Optional[str] = "nbs",
    lib_folder: Optional[str] = "nbmodular",
    clean: bool = False,
    keep_cwd: bool = False,
):
    """
    Check the content of a test repository.

    This function checks the content of a test repository based on the provided parameters.
    It verifies the structure and presence of notebooks and Python modules.

    Parameters
    ----------
    nb_paths : List[str]
        The list of notebook paths to check.
    expected_nbs : List[str], optional
        The list of expected notebook filenames, by default None.
    expected_py_modules : List[str], optional
        The list of expected Python module filenames, by default None.
    current_root : Optional[str], optional
        The current root directory of the test repository, by default None.
    new_root : Optional[str], optional
        The new root directory of the test repository, by default None.
    nbm_folder : str | None, optional
        The name of the folder containing the notebook modules, by default "nbm".
    tmp_folder : str | None, optional
        The name of the temporary folder, by default ".nbs".
    nbs_folder : str | None, optional
        The name of the folder containing the notebooks, by default "nbs".
    lib_folder : str | None, optional
        The name of the folder containing the Python modules, by default "nbmodular".
    clean : bool, optional
        Whether to clean the new root directory after checking, by default False.
    keep_cwd : bool, optional
        Whether to keep the current working directory after checking, by default False.

    Raises
    ------
    ValueError
        Raised when both clean and keep_cwd are set to True.
    """
    changed_dir = False
    if current_root is not None:
        assert Path(current_root).name == "nbmodular"
        new_wd = os.getcwd()

        assert Path(new_wd).resolve() == Path(f"{current_root}/{new_root}").resolve()
        os.chdir(current_root)
        changed_dir = True
    if new_root is not None:
        if not (Path(new_root) / "settings.ini").exists():
            if changed_dir:
                os.chdir(new_wd)
            raise FileNotFoundError(f"settings.ini not found in {new_root}")
        use_new_root = True
    else:
        new_root = "./"
        use_new_root = False

    if expected_nbs is not None:
        try:
            check_nbs(
                nb_paths, expected_nbs, new_root, nbm_folder, tmp_folder, nbs_folder
            )
        except AssertionError as e:
            if changed_dir:
                os.chdir(new_wd)
            raise e
    if expected_py_modules is not None:
        try:
            check_py_modules(nb_paths, expected_py_modules, new_root, lib_folder)
        except AssertionError as e:
            if changed_dir:
                os.chdir(new_wd)
            raise e
    if clean and use_new_root:
        shutil.rmtree(new_root)
    if keep_cwd and use_new_root:
        if clean:
            if changed_dir:
                os.chdir(new_wd)
            raise ValueError("keep_cwd can't be True if clean is True")
        os.chdir(new_root)


# %% ../nbs/test_utils.ipynb 101
def create_and_cd_to_new_root_folder(
    root_folder: str | Path,
    config_path: str | Path = "settings.ini",
) -> Path:
    """Creates `root_folder`, cds to it, and makes it act as *new root* (see below).

    In order to make it the new root, it copies the file `settings.ini`, which
    allows cd_root () find it and cd to it, and also allows some modules to load
    the global root's config from it.

    It assumes that

    Parameters
    ----------
    root_folder : str or Path
        Path to new root.
    config_path : str or Path, optional
        path to roo'ts config file, by default "settings.ini"

    Returns
    -------
    Path
        Absolute path to root_folder, as Path object.
    """
    config_path = Path(config_path)
    root_folder = Path(root_folder).absolute()
    root_folder.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(config_path, root_folder / config_path.name)
    os.chdir(root_folder)

    return root_folder


# %% ../nbs/test_utils.ipynb 103
def create_test_content(
    nbs: List[str] | str | None = None,
    nb_paths: Optional[List[str] | List[Path] | str | Path] = None,
    nb_folder: str = "nbm",
    py_modules: List[str] | str | None = None,
    py_paths: Optional[List[str] | List[Path] | str | Path] = None,
    lib_folder: Optional[str] = "nbmodular",
    cell_types_lists: List[List[str]] | None = None,
    cell_types_paths: Optional[str | Path] = None,
    cell_types_folder: str | Path = ".nbmodular",
    new_root: str = "new_test",
    config_path: str = "settings.ini",
) -> Tuple[str, List[str]]:
    """
    Create test content for notebooks.

    Parameters:
        nbs (List[str] | str): List of notebook texts or a single notebook text.
        nb_paths (Optional[List[str] | List[Path] | str | Path]): List of notebook paths or a single notebook path.
            If None, automatically generates notebook paths based on the number of notebooks.
        nb_folder (str): Name of the notebook folder.
        new_root (str): Name of the new root folder.
        config_path (str): Path to the configuration file.

    Returns:
        Tuple[str, List[str]]: A tuple containing the current root folder path and the list of notebook paths.
    """

    # we start from the root folder of our repo
    cd_root()
    current_root = os.getcwd()

    # Convert input texts into corresponding dicts with notebook structure
    nbs = texts2nbs(nbs) if nbs is not None else []

    # Generate list of nb_paths if None
    if nb_paths is None:
        nb_paths = [f"f{idx}" for idx in range(len(nbs))]
    else:
        if not isinstance(nb_paths, list):
            nb_paths = [nb_paths]
        if len(nb_paths) != len(nbs):
            raise ValueError("nb_paths must have same number of items as nbs")

    for nb, nb_path in zip(nbs, nb_paths):
        full_nb_path = Path(new_root) / nb_folder / nb_path
        full_nb_path.parent.mkdir(parents=True, exist_ok=True)
        write_nb(nb, full_nb_path)

    if py_modules is not None:
        py_modules = [py_modules] if isinstance(py_modules, str) else py_modules
        if py_paths is None:
            py_paths = [f"f{idx}" for idx in range(len(py_modules))]
        else:
            if not isinstance(py_paths, list):
                py_paths = [py_paths]
            if len(py_paths) != len(py_modules):
                raise ValueError(
                    "py_paths must have same number of items as py_modules"
                )

        for py_module, py_path in zip(py_modules, py_paths):
            full_py_path = Path(new_root) / lib_folder / py_path
            full_py_path.parent.mkdir(parents=True, exist_ok=True)
            full_py_path.write_text(py_module)

    if cell_types_lists is not None:
        if cell_types_paths is None:
            cell_types_paths = [f"f{idx}" for idx in range(len(cell_types_lists))]
        else:
            if len(cell_types_paths) != len(cell_types_lists):
                raise ValueError(
                    "cell_types_paths must have same number of items as cell_types_lists"
                )

        for cell_types, cell_types_path in zip(cell_types_lists, cell_types_paths):
            full_cell_types_path = Path(new_root) / cell_types_folder / cell_types_path
            full_cell_types_path.parent.mkdir(parents=True, exist_ok=True)
            joblib.dump(cell_types, full_cell_types_path)

    # Copy settings.ini in new root folder, so that this file
    # can be read later on by our export / import functions.
    # Also, cd to new root folder.
    _ = create_and_cd_to_new_root_folder(new_root, config_path)

    return current_root, nb_paths
