# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['imported_jupytext', 'set_handle_and_log_level', 'set_log_level', 'create_or_get_logger', 'get_repo_root_folder',
           'cd_root', 'get_config']

# %% ../nbs/utils.ipynb 2
# standard
import logging
import os
import shutil
from pathlib import Path
from typing import List, Tuple, Optional
from configparser import ConfigParser
import re

# 3rd party
import nbdev
from sklearn.utils import Bunch
from execnb.nbio import new_nb, write_nb

imported_jupytext = False
try:
    import jupytext as jp

    imported_jupytext = True
except ImportError:
    pass

# %% ../nbs/utils.ipynb 5
def set_handle_and_log_level(
    logger,
    log_level,
    handler: logging.StreamHandler | logging.FileHandler = logging.StreamHandler(),
):
    logger.setLevel(log_level)
    handler.setLevel(log_level)
    logger.addHandler(handler)

# %% ../nbs/utils.ipynb 7
def set_log_level(logger, log_level):
    logger.setLevel(log_level)
    for handler in logger.handlers:
        handler.setLevel(log_level)

# %% ../nbs/utils.ipynb 9
def create_or_get_logger(
    name: str = "nbmodular",
    log_level: Optional[str] = None,
    log_path: Optional[str] = "logs",
    file_name: str = "log.log",
    to_file=True,
):
    logger = logging.getLogger(name)
    if not logger.hasHandlers():
        set_handle_and_log_level(
            logger,
            log_level,
        )
        if to_file:
            full_log_path = (
                Path(log_path) / file_name if log_path is not None else Path(file_name)
            )
            full_log_path.parent.mkdir(parents=True, exist_ok=True)
            file_handler = logging.FileHandler(full_log_path)
            set_handle_and_log_level(logger, log_level, handler=file_handler)
    elif log_level is not None:
        set_log_level(logger, log_level)
    return logger

# %% ../nbs/utils.ipynb 11
def get_repo_root_folder(
    file_to_look_for_in_root_folder="settings.ini",
    max_parent_levels_to_traverse=10,
):
    """Gets root folder of repo where notebook is.

    It assumes that the root folder has a file called `file_to_look_for_in_root_folder`, which
    by default is `settings.ini`.
    """
    list_contents = os.listdir(".")
    traversed_parent_levels = 0
    while (
        file_to_look_for_in_root_folder not in list_contents
        and traversed_parent_levels < max_parent_levels_to_traverse
    ):
        traversed_parent_levels += 1
        os.chdir("..")
        list_contents = os.listdir(".")
    repo_root_folder = Path(".").resolve()
    return repo_root_folder

# %% ../nbs/utils.ipynb 12
def _cd_root_nbdev_impl():
    config = nbdev.config.get_config()
    os.chdir(config.config_path)

# %% ../nbs/utils.ipynb 13
def cd_root():
    repo_root_path = get_repo_root_folder()
    os.chdir(repo_root_path)

# %% ../nbs/utils.ipynb 15
def get_config(path: str = "settings.ini"):
    config = ConfigParser(delimiters=["="])
    config.read(path, encoding="utf-8")
    cfg = config["DEFAULT"]
    cfg.config_path = Path(path).resolve()
    return cfg
